version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/medical_visits_db
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - medical-visits-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - medical-visits-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - medical-visits-network

volumes:
  mongodb_data:

networks:
  medical-visits-network:
    driver: bridge
